title: "Towards a Generative Pictographic System for Cognitive Accessibility and Inclusive Communication"
author:
  name: "Herbert Spencer"
description: This presentation outlines the concerns of a practice-based doctoral investigation into the design of a generative pictographic system for cognitively accessible communication. The project is centred on adults with complex communication needs (CCN) and asks how such a system can support intuitive, culturally meaningful expression while promoting self-determination.
locale: en
baseurl: "prs" # 
url: "https://herbertspencer.net"
theme: null